// scripts/build-sets.js
// Generates src/engine/data/sets-lite.js — per-species EV spreads (EVs +
// nature + usage %) and the top item, from Smogon's monthly usage stats
// (e.g. gen9ou-0.txt). The engine uses this to replace its flat "252 EVs in
// the relevant stat, neutral nature" assumption with the spread people
// actually run: a physical Garchomp is 252 Atk / 0 SpA, a defensive Great
// Tusk is 252 HP / 252 Def / 0 SpD, and natures shift damage 5-10%.
//
// Source: https://www.smogon.com/stats/YYYY-MM/moveset/gen9ou-0.txt
// Each species block has an Items section and a Spreads section; a spread
// line is `Nature:EV1/EV2/EV3/EV4/EV5/EV6 pct%` with EV order
// HP/Atk/Def/SpA/SpD/Spe. We keep the top 3 spreads plus the top item,
// stored as:
//   "speciesId": "TopItem|Nature:ev,ev,ev,ev,ev,ev:pct;Nature:...:pct;..."
//
// The output is committed so builds/tests work offline; regenerate with:
//   npm run sets

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src', 'engine', 'data', 'sets-lite.js');
const MONTH = process.env.USAGE_MONTH ?? '2026-07';
const TIER = process.env.USAGE_TIER ?? 'gen9ou';
const SOURCE_URL = `https://www.smogon.com/stats/${MONTH}/moveset/${TIER}-0.txt`;
const MAX_SPREADS = 3;

const toID = (s) => String(s ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '');

// Parse the bordered text format into { speciesId: { item, spreads: [{nature, evs, pct}] } }.
function parseSource(text) {
  const out = {};
  let current = null;
  let section = null;
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (/^\+-/.test(trimmed)) continue; // borders
    if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
      const content = trimmed.slice(1, -1).trim();
      if (content === '') continue;
      if (current === null && !/^[A-Z]/.test(content)) continue;
      if (/^(Abilities|Items|Spreads|Moves|Tera Types|Teammates|Checks and Counters)$/.test(content)) {
        section = content;
        continue;
      }
      if (
        /^[A-Z][A-Za-z0-9 .\-']+$/.test(content) &&
        !content.includes('%') &&
        !content.includes(':') &&
        content !== 'Other'
      ) {
        // A species header (single word-ish, no % or :). Must be checked
        // AFTER the section names, which also match this shape.
        current = content;
        out[toID(current)] = { item: null, spreads: [] };
        section = null;
        continue;
      }
      if (current === null) continue;
      if (section === 'Items') {
        const m = /^(.+?)\s+([\d.]+)%$/.exec(content);
        if (m && !out[toID(current)].item) {
          const name = m[1].trim();
          if (name !== 'Other') out[toID(current)].item = name;
        }
      } else if (section === 'Spreads') {
        // `Relaxed:252/0/252/0/4/0 20.741%`
        const m = /^([A-Za-z]+):([\d/]+)\s+([\d.]+)%$/.exec(content);
        if (m) {
          const evs = m[2].split('/').map(Number);
          if (evs.length === 6 && evs.every((n) => Number.isFinite(n))) {
            out[toID(current)].spreads.push({
              nature: m[1],
              evs,
              pct: parseFloat(m[3]),
            });
          }
        }
      }
    }
  }
  return out;
}

const res = await fetch(SOURCE_URL);
if (!res.ok) throw new Error(`usage stats fetch failed: HTTP ${res.status} (${SOURCE_URL})`);
const raw = await res.text();
const parsed = parseSource(raw);

const out = {};
let speciesCount = 0;
let spreadCount = 0;
for (const [id, entry] of Object.entries(parsed)) {
  const spreads = entry.spreads
    .sort((a, b) => b.pct - a.pct)
    .slice(0, MAX_SPREADS)
    .map((s) => `${s.nature}:${s.evs.join(',')}:${s.pct.toFixed(1)}`);
  if (!spreads.length) continue;
  out[id] = `${entry.item ?? ''}|${spreads.join(';')}`;
  speciesCount += 1;
  spreadCount += spreads.length;
}

const header = [
  '// GENERATED by scripts/build-sets.js — do not edit by hand.',
  `// Top ${MAX_SPREADS} spreads (EVs + nature + usage %) + top item per species (${TIER}, ${MONTH}).`,
  '// Format: speciesId -> "Item|Nature:ev,ev,ev,ev,ev,ev:pct;..." (EV order HP/Atk/Def/SpA/SpD/Spe).',
  '// Replaces the flat 252-EV neutral-nature default with real competitive spreads.',
  '// Regenerate: npm run sets',
  '',
].join('\n');

const body = `export default Object.freeze(${JSON.stringify(out)});\n`;
writeFileSync(OUT, header + body);

const bytes = Buffer.byteLength(body);
console.log(`wrote ${OUT}`);
console.log(`species: ${speciesCount} | spreads: ${spreadCount} | ${(bytes / 1024).toFixed(1)} KB`);
console.log(`sample: ${JSON.stringify(Object.entries(out).slice(0, 3))}`);
