// scripts/build-usage.js
// Generates src/engine/data/usage-lite.js — per-species move usage percentages
// from Smogon's monthly usage stats (e.g. gen9ou-0.txt). The engine uses this
// to rank an opponent's *unrevealed* moves by how often people actually run
// them, instead of by raw base power.
//
// Source: https://www.smogon.com/stats/YYYY-MM/moveset/gen9ou-0.txt
// The file is a sequence of `+----+` bordered blocks; each block lists a
// species then sections (Abilities / Items / Spreads / Moves / ...) as
// `Name 99.999%` lines. We keep only the top moves per species, stored as
// `name:usage%` comma-joined entries, e.g.
//   "greattusk": "Rapid Spin:92.0,Headlong Rush:81.7,Ice Spinner:77.6,..."
//
// The output is committed so builds/tests work offline; regenerate with:
//   npm run usage

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { MOVES } from '@smogon/calc';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'src', 'engine', 'data', 'usage-lite.js');
const MONTH = process.env.USAGE_MONTH ?? '2026-07';
const TIER = process.env.USAGE_TIER ?? 'gen9ou';
const SOURCE_URL = `https://www.smogon.com/stats/${MONTH}/moveset/${TIER}-0.txt`;
const MAX_MOVES = 8; // keep the top N moves per species

const toID = (s) => String(s ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '');

// Parse the bordered text format into { speciesId: { moves: { name: pct } } }.
function parseSource(text) {
  const out = {};
  let current = null;
  let section = null;
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (/^\+\-/.test(trimmed)) continue; // borders
    if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
      const content = trimmed.slice(1, -1).trim();
      if (content === '') continue;
      if (current === null && !/^[A-Z]/.test(content)) continue;
      if (/^(Abilities|Items|Spreads|Moves|Tera Types|Teammates|Checks and Counters)$/.test(content)) {
        section = content;
        continue;
      }
      if (
        /^[A-Z][A-Za-z0-9 .\-']+$/.test(content) &&
        !content.includes('%') &&
        !content.includes(':') &&
        content !== 'Other'
      ) {
        // A species header (single word-ish, no % or :). Must be checked
        // AFTER the section names, which also match this shape.
        current = content;
        out[toID(current)] = { moves: {} };
        section = null;
        continue;
      }
      if (current === null) continue;
      if (section === 'Moves') {
        const m = /^(.+?)\s+([\d.]+)%$/.exec(content);
        if (m) {
          const name = m[1].trim();
          const pct = parseFloat(m[2]);
          if (name && !Number.isNaN(pct)) out[toID(current)].moves[name] = pct;
        }
      }
    }
  }
  return out;
}

const res = await fetch(SOURCE_URL);
if (!res.ok) throw new Error(`usage stats fetch failed: HTTP ${res.status} (${SOURCE_URL})`);
const raw = await res.text();
const usage = parseSource(raw);

// Only keep moves the damage calc knows (so they can actually be evaluated).
const moves9 = MOVES['9'] ?? MOVES[9];
const out = {};
let speciesCount = 0;
let moveCount = 0;
for (const [id, entry] of Object.entries(usage)) {
  const known = Object.entries(entry.moves)
    .filter(([name]) => name in moves9)
    .sort((a, b) => b[1] - a[1])
    .slice(0, MAX_MOVES);
  if (!known.length) continue;
  out[id] = known.map(([name, pct]) => `${name}:${pct.toFixed(1)}`).join(',');
  speciesCount += 1;
  moveCount += known.length;
}

const header = [
  '// GENERATED by scripts/build-usage.js — do not edit by hand.',
  `// Top ${MAX_MOVES} moves per species with Smogon usage % (${TIER}, ${MONTH}).`,
  '// Format: speciesId -> "Move:usage%,Move:usage%,..." — used to rank an',
  '// opponent\'s unrevealed moves by how often people actually run them.',
  '// Regenerate: npm run usage',
  '',
].join('\n');

const body = `export default Object.freeze(${JSON.stringify(out)});\n`;
writeFileSync(OUT, header + body);

const bytes = Buffer.byteLength(body);
console.log(`wrote ${OUT}`);
console.log(`species: ${speciesCount} | moves: ${moveCount} | ${(bytes / 1024).toFixed(1)} KB`);
console.log(`sample: ${JSON.stringify(Object.entries(out).slice(0, 2))}`);
